# Generated by Django 5.1.6 on 2025-02-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_cancelledlist_phone_alter_completedlist_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledlist',
            name='user_telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='completedlist',
            name='user_telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='generallist',
            name='user_telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notcomelist',
            name='user_telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
